### ISSUE TITLE
Death to Spies: Moment of Truth crashes on mission start (needs ID3DXSkinInfo::ConvertToIndexedBlendedMesh implementation)

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#110] opened 2014-10-31 14:50 UTC
https://bugs.winehq.org/show_bug.cgi?id=36449

no patch, but doesnt look that compilicated 

MSDN: http://msdn.microsoft.com/en-us/library/windows/desktop/bb174209%28v=vs.85%29.aspx

Source: http://source.winehq.org/git/wine.git/blob/0a993f14b4e254617e408f961fcb8f9464dd6a98:/dlls/d3dx9_36/skin.c#l397

**Comment by slackner** [comment] 2015-01-01 15:46
Wow, wrong parameters and noone noticed it? ^^ Patch was added in 9f43cabb0ae1b53fd799adbbb2a0c109355b6284.

I'll close this bug report since a real implementation is not necessary anymore.

**Closed by slackner** 2015-01-01 15:46 UTC
Labels: upstream-bug

**Comment by titan73** [comment] 2015-01-02 16:02
The small font issue is due the missing alpha channel caused by D3DXGetImageInfoFromFileInMemory returning format D3DFMT_X8R8G8B8 instead of D3DFMT_A8R8G8B8 for some TGA files. There is a same issue with BMP but without visual impact. The problems lie in windowscodec.dll as they are used for decoding BMP and TGA. Here is a workaround http://ix.io/fyA.

**Comment by titan73** [comment] 2015-01-02 16:03
The right link is http://ix.io/fyE.
