### ISSUE TITLE
[Glitches]FarCry 3 Directx9 needs NvApi implementation

### ISSUE THREAD

**Issue by berillions** [wine-compholio/wine-staging#271] opened 2015-01-12 17:42 UTC
Hi, 
As explain in this bug report : https://bugs.winehq.org/show_bug.cgi?id=35062, the map is drawn in the sea. (See screenshot in the bug report)

Confirmed by Stefan and I, it's a problem with Nvapi functions not implemented.

I launch today FarCry 3 with wine-stating 1.7.34 and this is the log with only the fixme about Nvapi : 
http://pastebin.com/5Mjmz0uK

The functions repeated continualy are : 
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0x1e9d8a31 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x4b708b54 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x9abdd40d is unimplemented!
fixme:nvapi:unimplemented_stub function 0x2926aaad is unimplemented!
fixme:nvapi:unimplemented_stub function 0xd22bdd7e is unimplemented!

Thanks,
Max

**Comment by DarkPlayer** [comment] 2015-01-12 17:56
I looked up the names for these ids:
```
0x33c7358c -> unknown
0x1e9d8a31 -> NvAPI_DISP_GetGDIPrimaryDisplayId
0x593e8644 -> unknown
0x4b708b54 -> NvAPI_D3D_GetCurrentSLIState
0x9abdd40d -> NvAPI_EnumNvidiaDisplayHandle
0x2926aaad -> NvAPI_SYS_GetDriverAndBranchVersion
0xd22bdd7e -> NvAPI_Unload
```
I don't know what the unknown functions are supposed to do, but the other ones don't seem to affect  rendering. I will try to write stubs for them, maybe Far Cry 3 will use additional functions from nvapi if they succeed.

**Comment by slackner** [comment] 2015-01-12 18:16
I assume the graphical glitches are identical between regular wine and wine-staging, so marking as an upstream bug.

**Comment by DarkPlayer** [comment] 2015-01-12 23:02
I am currently writing stubs for the missing functions, but can you try Far Cry 3 again with `WINEDEBUG=+nvapi` and check whether NvAPI_D3D9_StretchRectEx gets called?

**Comment by DarkPlayer** [comment] 2015-01-13 01:27
Can you apply the 9 patches from https://dl.dropboxusercontent.com/u/61413222/nvapi_farcry3.tar.gz? They should implement all requested functions.

**Comment by DarkPlayer** [comment] 2015-01-13 02:26
I pushed the patches into the repository, so you can directly test the current git version.

**Comment by berillions** [comment] 2015-01-13 05:25
Hi Michael,

I tried your patch and it's great, all glitches are disappear.
Thanks you ;)

**Comment by slackner** [comment] 2015-01-13 06:04
Ah, that is really nice - but almost a bit surprising, because we have no real implementation for any of these d3d functions so far.

Could you maybe attach a log, this should show which of our stubs are really needed.
Moreover, just to be sure that nvapi really makes a difference, could you test with and without `WINEDLLOVERRIDES="nvapi="`?

**Comment by berillions** [comment] 2015-01-13 16:22
This is the latest log after to apply your patch : 
http://pastebin.com/TZUakuG1

Screenshot with nvapi enabled : 
![nvapi_enabled](https://cloud.githubusercontent.com/assets/3606036/5723943/56f34736-9b48-11e4-89d2-74ed8a2d2d05.png)

Screenshot with nvapi disabled : 
![nvapi_disabled](https://cloud.githubusercontent.com/assets/3606036/5723965/7508b59e-9b48-11e4-96c4-c65396dcd902.png)

**Comment by slackner** [comment] 2015-01-13 16:32
The remaining unimplement stubs are:

```
0xDC6DC8D3 -> NvAPI_Mosaic_GetDisplayViewportsByResolution
0xEE1370CF -> NvAPI_GetLogicalGPUFromDisplay
```

Nevertheless it seems like those stubs are not really critical. Nice to see that this was sufficient to make the game happy.

**Comment by DarkPlayer** [comment] 2015-01-14 21:03
I wrote a stub for `NvAPI_GetLogicalGPUFromDisplay` but I am not sure what we should do about `NvAPI_Mosaic_GetDisplayViewportsByResolution`.

I use the mosaic mode of NVIDIA to control two monitors attached to two different graphic cards. The mosaic mode does basically the same as xinerama, but has some advantages if you are using multiple graphic cards. My understanding of this function is that you pass a display handle and a new resolution for this display and you get back an array which describes how the display are positioned after the resolution change. At the moment our nvapi implementation simulates a single display, though we could theoretically do better using our EnumDisplay fix. Even with this fix applied we would still need to mime the logic of the XServer to calculate the correct positions of the displays.

The easiest solution would be to return `NVAPI_MOSAIC_NOT_ACTIVE` but this might cause problems on multi monitor setups. Any opinions on this?

**Comment by DarkPlayer** [comment] 2015-01-14 21:29
`NvAPI_GetLogicalGPUFromDisplay` was added in 93764fd3d417f837cf2a111e0d4aab23f7ce7d5f.

**Comment by slackner** [comment] 2016-01-04 17:43
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.

**Closed by slackner** 2016-01-04 17:43 UTC
Labels: upstream-bug
