### ISSUE TITLE
L.A. Noire 1.3 (Steam version) crashes during upload of WINED3DFMT_DXT1 volume texture

### ISSUE THREAD

**Issue by deri82** [wine-compholio/wine-staging#196] opened 2014-11-25 21:01 UTC
Since you have some DX* patches, it could be worth to try this game with some of those patches.

https://bugs.winehq.org/show_bug.cgi?id=35900

**Comment by slackner** [comment] 2015-01-19 08:09
@titan73: How difficult do you think would it be to allow DXT format compressions for volume textures? Or does this already work with our existing patch?

**Comment by titan73** [comment] 2015-01-19 09:15
@slackner: This will not work as is but we have all the bases for that. Volume textures are just slice of textures. This is not a big work but having access to the game would help a lot.

**Comment by titan73** [comment] 2015-01-27 06:41
@deri82: btw did you test the patch in comment 14 https://bugs.winehq.org/show_bug.cgi?id=35900#c14?

**Comment by deri82** [comment] 2015-01-27 12:04
I havent tried the patch mentiond. I have issues to getting into the point I have been before.

the game complains now

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'SecureDownloadAPI, 

I have seen this file mentioned at some bug report upstream.

**Comment by titan73** [comment] 2015-01-27 12:13
Is it a regression in wine?

**Comment by deri82** [comment] 2015-01-27 12:20
No. I needed dotnet20 to bypass the problem. I am very positive about this game now. Because I launched it with wine. It opened fullscreen game window. I has never done that before. Also the window was all pink. Remember the pink airplane yesterday? Going to try wine-staging now.

**Comment by deri82** [comment] 2015-01-27 12:28
I quess I am now somepoint that AF has been and I havent been before.

https://bugs.winehq.org/show_bug.cgi?id=35900#c14

It feels to do the synchronizing forever

Are these important?

err:d3d:wined3d_debug_callback 0x40093060: "GL_INVALID_ENUM in glTexImage3D(target can't be compressed)".
err:d3d_texture:texture3d_prepare_texture >>>>>>>>>>>>>>>>> GL_INVALID_ENUM (0x500) from glTexImage3D @ texture.c / 1468
err:d3d:wined3d_debug_callback 0x40093060: "GL_INVALID_OPERATION in glTexSubImage3D(invalid texture image)".
err:d3d_surface:wined3d_volume_upload_data >>>>>>>>>>>>>>>>> GL_INVALID_OPERATION (0x502) from glTexSubImage3D @ volume.c / 91

**Comment by titan73** [comment] 2015-01-27 12:37
Yeah. It tries to create a volume texture but OpenGL does not support it as ST3C extension only apply on 2D textures.

**Comment by titan73** [comment] 2015-01-27 12:44
So either we make the game think dxt is not supported for volume texture or we convert to a format that OpenGL can deal with (normal texture format or using another OpenGL extension).
It does not seem there is a easy way to query this feature so AF patch tried to just fail at texture creation to see if the game deal with that and fallback to another format.

**Comment by deri82** [comment] 2015-01-27 13:51
Closing this for now. I am at dead end currently.

**Comment by slackner** [comment] 2015-01-27 13:53
Why was it closed? The problem still exists. I would like to hear @titan73's opinion first if this is impossible to solve before closing this issue where he is probably also currently working on.

**Comment by titan73** [comment] 2015-01-27 14:32
Keep this bug open. I'm working on it. This will take some time as I would like to understand what the game want to do and how DXT textures on volume work on Windows. Don't worry, this will not take years. ;)
Btw I was a bit surprised to read this https://msdn.microsoft.com/en-us/library/windows/hardware/ff553847(v=vs.85).aspx.

**Comment by titan73** [comment] 2015-01-27 14:32
You can move this bug to bugzilla if you wish.

**Comment by deri82** [comment] 2015-01-27 14:33
Move or keep here? I can open new bug report if you want.

**Comment by titan73** [comment] 2015-01-27 14:34
yep but @slackner may know more what to do about it.

**Comment by slackner** [comment] 2015-01-27 19:21
Lets keep it here for now, otherwise the previous conversation and ideas are lost.

**Comment by deri82** [comment] 2015-01-27 23:49
I tried the game again with wine and on top of that focht made patch for rejecting volume textures. Game really dont like it. It gives an error dialogue about not able to make volume textures.

**Comment by titan73** [comment] 2015-01-28 17:39
@deri82 : Is possible to retest w/o AF patch with WINEDEBUG=+d3d,+d3d9,+winediag,+d3d_texture,+d3d_surface? (yes d3d_surface channel in volume.c ;))
I will look at the logs first and after try do some testing on the real games.

**Comment by titan73** [comment] 2015-01-28 18:02
Can you add also +d3dx9?
Can you test with both builtin and native d3dx9? And with the log for each of them?

**Comment by deri82** [comment] 2015-01-28 18:06
Would be easier to give you access. These logs are huge. I did the 1st log with all those channels you mentioned, started wine notepad on another console and still the log was 1.6Gb, compressed almost 100Mb. I dont know what program to use to open these, because I have difficulties to open (8Gb memory).

**Comment by titan73** [comment] 2015-01-28 18:13
Ah indeed. Ok let's find a schedule this week-end then. :)

**Comment by deri82** [comment] 2015-01-28 18:13
fixme:d3d:swapchain_init The application requested more than one back buffer, this is not properly supported.
Please configure the application to use double buffering (1 back buffer) if possible.
trace:d3d_texture:wined3d_texture_create device 0x3301f098, desc 0x331658, level_count 1, surface_flags 0x1, data (nil), parent 0x330164f0, parent_ops 0xf6efab78, texture 0x331654.
trace:d3d_texture:wined3d_texture_init texture 0x33076968, texture_ops 0xf6eb4f14, layer_count 1, level_count 1, resource_type WINED3D_RTYPE_TEXTURE, format WINED3DFMT_B8G8R8X8_UNORM, multisample_type 0, multisample_quality 0, usage 0, pool WINED3D_POOL_DEFAULT, width 1920, height 1080, depth 1, surface_flags 0x1, device 0x3301f098, parent 0x330164f0, parent_ops 0xf6efab78, resource_ops 0xf6eb4f08.
trace:d3d_texture:texture_init xf(1.000000) yf(1.000000)
trace:d3d_surface:wined3d_surface_create container 0x33076968, width 1920, height 1080, format WINED3DFMT_B8G8R8X8_UNORM, usage 0 (0), pool WINED3D_POOL_DEFAULT, multisample_type 0, multisample_quality 0, target 0xde1, level 0, layer 0, flags 0x1, surface 0x3315c4.
warn:d3d_surface:surface_init Creating a lockable surface with a POOL of DEFAULT, that doesn't specify DYNAMIC usage.
trace:d3d_surface:surface_validate_location surface 0x33076af8, location WINED3D_LOCATION_SYSMEM.
trace:d3d_surface:surface_private_setup surface 0x33076af8.
trace:d3d_texture:wined3d_texture_get_parent texture 0x33076968.
trace:d3d_surface:wined3d_surface_get_resource surface 0x33076af8.
trace:d3d_surface:wined3d_surface_create Created surface 0x33076af8, parent 0x33016520, parent_ops 0xf6efac64.
trace:d3d_texture:texture_init Created surface level 0 @ 0x33076af8.
trace:d3d_texture:wined3d_texture_create Created texture 0x33076968.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_incref surface 0x33076af8, container 0x33076968.
trace:d3d_texture:wined3d_texture_incref texture 0x33076968, swapchain (nil).
trace:d3d_texture:wined3d_texture_incref 0x33076968 increasing refcount to 2.
trace:d3d_texture:wined3d_texture_decref texture 0x33076968, swapchain (nil).
trace:d3d_texture:wined3d_texture_decref 0x33076968 decreasing refcount to 1.
trace:d3d_surface:wined3d_surface_get_parent surface 0x33076af8.
trace:d3d_surface:surface_validate_location surface 0x33076af8, location WINED3D_LOCATION_DRAWABLE.
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33076af8, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_RGB | WINED3D_LOCATION_TEXTURE_SRGB | W.
trace:d3d_texture:wined3d_texture_create device 0x3301f098, desc 0x331658, level_count 1, surface_flags 0x1, data (nil), parent 0x330164f0, parent_ops 0xf6efab78, texture 0x331654.
trace:d3d_texture:wined3d_texture_init texture 0x33077258, texture_ops 0xf6eb4f14, layer_count 1, level_count 1, resource_type WINED3D_RTYPE_TEXTURE, format WINED3DFMT_B8G8R8X8_UNORM, multisample_type 0, multisample_quality 0, usage WINED3DUSAGE_RENDERTARGET, pool WINED3D_POOL_DEFAULT, width 1920, height 1080, depth 1, surface_flags 0x1, device 0x3301f098, parent 0x330164f0, parent_ops 0xf6efab78, resource_ops 0xf6eb4f08.
trace:d3d_texture:texture_init xf(1.000000) yf(1.000000)
trace:d3d_surface:wined3d_surface_create container 0x33077258, width 1920, height 1080, format WINED3DFMT_B8G8R8X8_UNORM, usage WINED3DUSAGE_RENDERTARGET (0x1), pool WINED3D_POOL_DEFAULT, multisample_type 0, multisample_quality 0, target 0xde1, level 0, layer 0, flags 0x1, surface 0x3315c4.
trace:d3d_surface:surface_validate_location surface 0x33077400, location WINED3D_LOCATION_SYSMEM.
trace:d3d_surface:surface_private_setup surface 0x33077400.
trace:d3d_texture:wined3d_texture_get_parent texture 0x33077258.
trace:d3d_surface:wined3d_surface_get_resource surface 0x33077400.
trace:d3d_surface:wined3d_surface_create Created surface 0x33077400, parent 0x33077518, parent_ops 0xf6efac64.
trace:d3d_texture:texture_init Created surface level 0 @ 0x33077400.
trace:d3d_texture:wined3d_texture_create Created texture 0x33077258.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_incref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_incref texture 0x33077258, swapchain (nil).
trace:d3d_texture:wined3d_texture_incref 0x33077258 increasing refcount to 2.
trace:d3d_texture:wined3d_texture_decref texture 0x33077258, swapchain (nil).
trace:d3d_texture:wined3d_texture_decref 0x33077258 decreasing refcount to 1.
trace:d3d_surface:wined3d_surface_get_parent surface 0x33077400.
trace:d3d_texture:wined3d_texture_create device 0x3301f098, desc 0x331658, level_count 1, surface_flags 0x1, data (nil), parent 0x330164f0, parent_ops 0xf6efab78, texture 0x331654.
trace:d3d_texture:wined3d_texture_init texture 0x33077550, texture_ops 0xf6eb4f14, layer_count 1, level_count 1, resource_type WINED3D_RTYPE_TEXTURE, format WINED3DFMT_B8G8R8X8_UNORM, multisample_type 0, multisample_quality 0, usage WINED3DUSAGE_RENDERTARGET, pool WINED3D_POOL_DEFAULT, width 1920, height 1080, depth 1, surface_flags 0x1, device 0x3301f098, parent 0x330164f0, parent_ops 0xf6efab78, resource_ops 0xf6eb4f08.
trace:d3d_texture:texture_init xf(1.000000) yf(1.000000)
trace:d3d_surface:wined3d_surface_create container 0x33077550, width 1920, height 1080, format WINED3DFMT_B8G8R8X8_UNORM, usage WINED3DUSAGE_RENDERTARGET (0x1), pool WINED3D_POOL_DEFAULT, multisample_type 0, multisample_quality 0, target 0xde1, level 0, layer 0, flags 0x1, surface 0x3315c4.
trace:d3d_surface:surface_validate_location surface 0x330776f8, location WINED3D_LOCATION_SYSMEM.
trace:d3d_surface:surface_private_setup surface 0x330776f8.
trace:d3d_texture:wined3d_texture_get_parent texture 0x33077550.
trace:d3d_surface:wined3d_surface_get_resource surface 0x330776f8.
trace:d3d_surface:wined3d_surface_create Created surface 0x330776f8, parent 0x33077810, parent_ops 0xf6efac64.
trace:d3d_texture:texture_init Created surface level 0 @ 0x330776f8.
trace:d3d_texture:wined3d_texture_create Created texture 0x33077550.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077550, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_incref surface 0x330776f8, container 0x33077550.
trace:d3d_texture:wined3d_texture_incref texture 0x33077550, swapchain (nil).
trace:d3d_texture:wined3d_texture_incref 0x33077550 increasing refcount to 2.
trace:d3d_texture:wined3d_texture_decref texture 0x33077550, swapchain (nil).
trace:d3d_texture:wined3d_texture_decref 0x33077550 decreasing refcount to 1.
trace:d3d_surface:wined3d_surface_get_parent surface 0x330776f8.
trace:d3d_texture:wined3d_texture_create device 0x3301f098, desc 0x331658, level_count 1, surface_flags 0x1, data (nil), parent 0x33011120, parent_ops 0xf6efab78, texture 0x331654.
trace:d3d_texture:wined3d_texture_init texture 0x3309dca0, texture_ops 0xf6eb4f14, layer_count 1, level_count 1, resource_type WINED3D_RTYPE_TEXTURE, format WINED3DFMT_D16_UNORM, multisample_type 0, multisample_quality 0, usage WINED3DUSAGE_DEPTHSTENCIL, pool WINED3D_POOL_DEFAULT, width 1920, height 1080, depth 1, surface_flags 0x1, device 0x3301f098, parent 0x33011120, parent_ops 0xf6efab78, resource_ops 0xf6eb4f08.
trace:d3d_texture:texture_init xf(1.000000) yf(1.000000)
trace:d3d_surface:wined3d_surface_create container 0x3309dca0, width 1920, height 1080, format WINED3DFMT_D16_UNORM, usage WINED3DUSAGE_DEPTHSTENCIL (0x2), pool WINED3D_POOL_DEFAULT, multisample_type 0, multisample_quality 0, target 0xde1, level 0, layer 0, flags 0x1, surface 0x3315c4.
trace:d3d_surface:surface_validate_location surface 0x33077860, location WINED3D_LOCATION_SYSMEM.
trace:d3d_surface:surface_private_setup surface 0x33077860.
trace:d3d_texture:wined3d_texture_get_parent texture 0x3309dca0.
trace:d3d_surface:wined3d_surface_get_resource surface 0x33077860.
trace:d3d_surface:wined3d_surface_create Created surface 0x33077860, parent 0x3309de30, parent_ops 0xf6efac64.
trace:d3d_texture:texture_init Created surface level 0 @ 0x33077860.
trace:d3d_texture:wined3d_texture_create Created texture 0x3309dca0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_incref surface 0x33077860, container 0x3309dca0.
trace:d3d_texture:wined3d_texture_incref texture 0x3309dca0, swapchain (nil).
trace:d3d_texture:wined3d_texture_incref 0x3309dca0 increasing refcount to 2.
trace:d3d_texture:wined3d_texture_decref texture 0x3309dca0, swapchain (nil).
trace:d3d_texture:wined3d_texture_decref 0x3309dca0 decreasing refcount to 1.
trace:d3d_surface:wined3d_surface_get_parent surface 0x33077860.
trace:d3d_texture:wined3d_texture_incref texture 0x3309dca0, swapchain (nil).
trace:d3d_texture:wined3d_texture_incref 0x3309dca0 increasing refcount to 2.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_decref surface 0x33077860, container 0x3309dca0.
trace:d3d_texture:wined3d_texture_decref texture 0x3309dca0, swapchain (nil).
trace:d3d_texture:wined3d_texture_decref 0x3309dca0 decreasing refcount to 1.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_incref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_texture:texture2d_prepare_texture texture 0x33077258, format WINED3DFMT_B8G8R8X8_UNORM.
trace:d3d_texture:wined3d_texture_bind texture 0x33077258, context 0x3309c9c8, srgb 0.
trace:d3d_texture:wined3d_texture_bind glGenTextures call ok texture.c / 181
trace:d3d_texture:wined3d_texture_bind Generated texture 61.
trace:d3d_texture:wined3d_texture_bind Setting GL_TEXTURE_MAX_LEVEL to 0.
trace:d3d_texture:wined3d_texture_bind glTexParameteri(target, GL_TEXTURE_MAX_LEVEL, texture->level_count) call ok texture.c / 237
trace:d3d_texture:texture2d_prepare_texture internal 0x8c41, format 0x80e1, type 0x8367.
trace:d3d_texture:texture2d_prepare_texture surface 0x33077400, target 0xde1, level 0, width 1920, height 1080.
trace:d3d_texture:texture2d_prepare_texture glTexImage2D call ok texture.c / 896
trace:d3d_texture:texture2d_prepare_texture texture 0x3309dca0, format WINED3DFMT_D16_UNORM.
trace:d3d_texture:wined3d_texture_bind texture 0x3309dca0, context 0x3309c9c8, srgb 0.
trace:d3d_texture:wined3d_texture_bind glGenTextures call ok texture.c / 181
trace:d3d_texture:wined3d_texture_bind Generated texture 62.

That's with WINEDEBUG=+d3d_texture,+d3d_surface, wine Steam -no-dwrite &> debug2.log

Only few libreoffice pages.

**Comment by deri82** [comment] 2015-01-28 18:18
This looked interesting so I paste this here

trace:d3d_surface:wined3d_surface_get_parent surface 0x33077400.
trace:d3d_surface:wined3d_surface_incref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_incref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_surface:wined3d_surface_decref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_decref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:surface_load_location surface 0x33077400, location WINED3D_LOCATION_TEXTURE_RGB.
trace:d3d_surface:surface_load_location Location already up to date.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_surface:surface_validate_location surface 0x33076af8, location WINED3D_LOCATION_DRAWABLE.
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33076af8, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_RGB | WINED3D_LOCATION_TEXTURE_SRGB | W.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_HANDLE_INFORMATION
fixme:imm:ImmGetOpenStatus (0x16eb68): semi-stub
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_surface:surface_modify_ds_location surface 0x33077860, new location 0x20, w 1920, h 1080.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:surface_validate_location surface 0x33077400, location WINED3D_LOCATION_TEXTURE_RGB.
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33077400, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_SRGB | WINED3D_LOCATION_DRAWABLE | WINE.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_get_parent surface 0x33077400.
trace:d3d_surface:wined3d_surface_incref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_incref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_surface:wined3d_surface_decref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_decref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:surface_load_location surface 0x33077400, location WINED3D_LOCATION_TEXTURE_RGB.
trace:d3d_surface:surface_load_location Location already up to date.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_surface:surface_validate_location surface 0x33076af8, location WINED3D_LOCATION_DRAWABLE.
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33076af8, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_RGB | WINED3D_LOCATION_TEXTURE_SRGB | W.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
fixme:ver:GetCurrentPackageId (0x33e7f4 (nil)): stub
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x3309dca0, sub_resource_idx 0.
trace:d3d_surface:surface_modify_ds_location surface 0x33077860, new location 0x20, w 1920, h 1080.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:surface_validate_location surface 0x33077400, location WINED3D_LOCATION_TEXTURE_RGB.
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33077400, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_SRGB | WINED3D_LOCATION_DRAWABLE | WINE.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:wined3d_surface_get_parent surface 0x33077400.
trace:d3d_surface:wined3d_surface_incref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_incref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_surface:wined3d_surface_decref surface 0x33077400, container 0x33077258.
trace:d3d_texture:wined3d_texture_decref texture 0x33077258, swapchain 0x330762b0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_surface:surface_load_location surface 0x33077400, location WINED3D_LOCATION_TEXTURE_RGB.
trace:d3d_surface:surface_load_location Location already up to date.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33077258, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_texture:wined3d_texture_get_sub_resource texture 0x33076968, sub_resource_idx 0.
trace:d3d_surface:surface_validate_location surface 0x33076af8, location

**Comment by titan73** [comment] 2015-01-28 21:38
There is no DXT related lines but wooooo these lines are realy weird:
fixme:d3d:wined3d_debug_location Unrecognized location flag(s) 0xfffffc00.
trace:d3d_surface:surface_invalidate_location surface 0x33076af8, location WINED3D_LOCATION_DISCARDED | WINED3D_LOCATION_SYSMEM | WINED3D_LOCATION_USER_MEMORY | WINED3D_LOCATION_DIB | WINED3D_LOCATION_BUFFER | WINED3D_LOCATION_TEXTURE_RGB | WINED3D_LOCATION_TEXTURE_SRGB | W.

**Comment by deri82** [comment] 2015-01-28 21:53
I quess you know this better but I found this

https://msdn.microsoft.com/en-us/library/dn643732.aspx

when I searched

B8G8R8X8 which is mentioned in log

Original format (from)
DXGI_FORMAT_B8G8R8X8_UNORM
Compressed format (to)
BC1 (formerly DXT1)

according to focht analyze the bug needs DXT1 volume textures...

**Comment by titan73** [comment] 2015-01-28 22:06
BC1,2,3 is the new standard name for DXT1,3,5. DXT2,4 use premultiplied alpha and are useless and thus were almost never used.
This is D3D11 stuff tough.

**Comment by slackner** [comment] 2016-01-04 17:41
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.

**Closed by slackner** 2016-01-04 17:41 UTC
Labels: upstream-bug
