### ISSUE TITLE
The Longest Journey patch

### ISSUE THREAD

**Issue by i30817** [wine-compholio/wine-staging#232] opened 2014-12-24 04:36 UTC
It's bitrotted and lingering on the bug report since version 1.3
https://bugs.winehq.org/show_bug.cgi?id=11819

Could it finally be fixed up and hopefully upstreamed?

**Comment by i30817** [comment] 2015-01-05 11:46
I tried to apply the last patches here to plain wine git and the 3d characters are still partially rendered (although they're not shadows anymore).

**Comment by i30817** [comment] 2015-01-05 12:03
Should i maybe have reverted the commits instead of applying the 5 patches?

**Comment by compholio** [comment] 2015-01-05 17:34
@i30817: You should just need to apply the patches from this comment:

**Comment by i30817** [comment] 2015-01-05 18:07
I did. And the patch below those 4 for the pink text. 
It simply doesn't seem to work in here (radeon, Gallium driver)

**Comment by i30817** [comment] 2015-01-05 18:26
Yes, its applied... just not working. I followed the 'build wine in biarch' guide until the very last part ((i didn't overwrite my ppa wine, just called the new ones, both 32 and 64 bits on a new TLJ prefix).

logs like this seem to occur if that comment fixme is uncommented:
fixme:ddraw:d3d_viewport_TransformVertices 0: (-43.79,-0.00,-72.93)=>(0.50,-0.78,0.94,0.00)=>(0.50,-0.78,0.94,0.00)=>(479.6,361.4,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 1: (23.09,-0.00,-72.93)=>(0.49,-0.62,0.95,0.00)=>(0.49,-0.62,0.95,0.00)=>(477.6,331.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 2: (23.09,0.00,-72.93)=>(0.49,-0.62,0.95,0.00)=>(0.49,-0.62,0.95,0.00)=>(477.6,331.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 3: (-43.79,0.00,-72.93)=>(0.50,-0.78,0.94,0.00)=>(0.50,-0.78,0.94,0.00)=>(479.6,361.4,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 4: (-43.79,-0.00,43.01)=>(0.03,-0.73,0.94,0.00)=>(0.03,-0.73,0.94,0.00)=>(330.9,351.5,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 5: (23.09,-0.00,43.01)=>(0.07,-0.57,0.96,0.00)=>(0.07,-0.57,0.96,0.00)=>(343.1,323.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 6: (23.09,0.00,43.01)=>(0.07,-0.57,0.96,0.00)=>(0.07,-0.57,0.96,0.00)=>(343.1,323.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 7: (-43.79,0.00,43.01)=>(0.03,-0.73,0.94,0.00)=>(0.03,-0.73,0.94,0.00)=>(330.9,351.5,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 0: (-37.54,-0.36,-72.92)=>(0.50,-0.77,0.94,0.00)=>(0.50,-0.77,0.94,0.00)=>(479.3,358.7,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 1: (23.06,-0.36,-72.92)=>(0.49,-0.62,0.95,0.00)=>(0.49,-0.62,0.95,0.00)=>(477.6,331.8,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 2: (23.06,93.18,-72.92)=>(0.51,-0.03,0.95,0.00)=>(0.51,-0.03,0.95,0.00)=>(482.3,224.7,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 3: (-37.54,93.18,-72.92)=>(0.51,-0.13,0.93,0.00)=>(0.51,-0.13,0.93,0.00)=>(484.7,241.8,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 4: (-37.54,-0.36,39.88)=>(0.05,-0.72,0.94,0.00)=>(0.05,-0.72,0.94,0.00)=>(336.0,349.3,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 5: (23.06,-0.36,39.88)=>(0.08,-0.58,0.96,0.00)=>(0.08,-0.58,0.96,0.00)=>(346.6,323.9,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 6: (23.06,93.18,39.88)=>(0.09,-0.01,0.95,0.00)=>(0.09,-0.01,0.95,0.00)=>(347.4,219.7,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 7: (-37.54,93.18,39.88)=>(0.05,-0.09,0.94,0.00)=>(0.05,-0.09,0.94,0.00)=>(336.5,235.8,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 0: (-43.79,-0.00,-72.93)=>(0.50,-0.78,0.94,0.00)=>(0.50,-0.78,0.94,0.00)=>(479.6,361.4,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 1: (23.09,-0.00,-72.93)=>(0.49,-0.62,0.95,0.00)=>(0.49,-0.62,0.95,0.00)=>(477.6,331.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 2: (23.09,0.00,-72.93)=>(0.49,-0.62,0.95,0.00)=>(0.49,-0.62,0.95,0.00)=>(477.6,331.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 3: (-43.79,0.00,-72.93)=>(0.50,-0.78,0.94,0.00)=>(0.50,-0.78,0.94,0.00)=>(479.6,361.4,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 4: (-43.79,-0.00,43.01)=>(0.03,-0.73,0.94,0.00)=>(0.03,-0.73,0.94,0.00)=>(330.9,351.5,0.9,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 5: (23.09,-0.00,43.01)=>(0.07,-0.57,0.96,0.00)=>(0.07,-0.57,0.96,0.00)=>(343.1,323.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 6: (23.09,0.00,43.01)=>(0.07,-0.57,0.96,0.00)=>(0.07,-0.57,0.96,0.00)=>(343.1,323.3,1.0,0.0).
fixme:ddraw:d3d_viewport_TransformVertices 7: (-43.79,0.00,43.01)=>(0.03,-0.73,0.94,0.00)=>(0.03,-0.73,0.94,0.00)=>(330.9,351.5,0.9,0.0).

**Comment by i30817** [comment] 2015-01-06 11:47
Tried to apply on top of the staging patches from this repository to see if it was some missing thing from here, but the patch3, the second revert fails to apply so i guess not.

**Comment by titan73** [comment] 2015-01-06 16:13
This is probably due to csmt changes. The patches are meant to be used with bare wine.

**Comment by i30817** [comment] 2015-01-06 16:45
Frustating, but i'm confident you'll work it out ;)

**Comment by titan73** [comment] 2015-01-06 19:43
nvidia GT 560M + this s**t of unity ;)

**Comment by slackner** [comment] 2015-01-07 10:23
Well, the main question is what the correct way is to fix this issue. Having a rebased version of the patch is only the first step... :/ It most likely involves writing a huge amount of additional tests until we can be sure whats the expected behaviour, and especially how to solve all the regressions.

**Comment by i30817** [comment] 2015-01-07 11:24
I'm getting mysterious results while reverting applied patches and rebuilding. If i just do 
patch -p1 -R < 5.diff
and make again it still doesn't have pink text, bizarre.

**Comment by titan73** [comment] 2015-01-07 12:01
Did you ever see the pink text? Maybe this problem appear in particular environment.

**Comment by i30817** [comment] 2015-01-07 12:25
I did.

**Comment by i30817** [comment] 2015-01-07 12:46
Anyway with this i was able to test:
with patch 1, 2, 3, 4, 5 i get partial characters
with patch 1, 2, 4, 5 i get partial characters
with patch 1, 4, 5 i get no characters (only slightly glitchy shadows, not black characters)
with patch 4, 5 i get the same as above.

**Comment by titan73** [comment] 2015-01-07 12:58
What are these 1 to 5 patches you're referring to?

**Comment by titan73** [comment] 2015-01-07 15:20
I don't unserstand the combinations you tested.

Here are the meaningful ones where each problems are completely separates:

Note that patch 1 & 2 must be applied together as they are part of the same subsystem.

Characters problem:
a) no patch
b) patch 1 & 2
c) patch 1 & 2 + patch 3

Gray popup problem when quitting:
a) no patch
b) patch 4

Pink text outline problem in menu & game:
a) no patch
b) patch 5

That would be nice to have screenshots for each combinations regarding the characters problem.

Here are the patch for the record:
1) http://ix.io/dXw (rebased patch for viewport 2 support in TransformVertices)
2) http://ix.io/dXA (partial revert of 4a30db74b1dbad885941970e7caf9815abd7826d)
3) http://ix.io/e15 (revert of 439097c810bdcb2bd3f838d2ee47369d1f4d7e8a)
4) http://ix.io/e8l (workaound/fix for gray popup issue)
5) http://ix.io/ev5 (workaround for pink text outline)

These patches have been rebased for and successfully tested with wine 1.7.33 and. If you have additional patches (wine-staging or latest wine) and encounter problem, retry with 1.7.33.

**Comment by slackner** [comment] 2015-01-07 15:39
@i30817: You should also make sure that you undo all previously applied changes before you test a new patchset. The patches have to be applied with "patch -p1 < ....", so the commandline should not contain "-R" like you wrote above. When everything goes well the patch-process should exit without any error, if you get warnings about "reversed patch detected" or "failed to apply" then something is wrong with your wine source tree. Reset it to the original state and start from scratch, otherwise there is no guarantee that it will work.

**Comment by slackner** [comment] 2015-01-07 15:41
And, forgot to mention: usually the order of the patches does also matter, so apply them exactly in the given order.

**Comment by titan73** [comment] 2015-01-07 15:55
Yeah, patch 1 & 2 come together and 2 must be applied after 1. All other patches are independant.

**Comment by i30817** [comment] 2015-01-07 16:26
I did no mistake. It's simply not working for me. Also the '-R' was when i was specifically trying to revert to figure out the weirdness (which was, that i was compiling wine64 and trying to run the TLJ with that, which redirected to the system wine because it's a 32 bits exectable. Building on the lxc container worked for testing, but as i say the patches 1 2 and 3 don't work here).

**Comment by titan73** [comment] 2015-01-07 17:06
Can you make screenshots? With:
a) patch 1 & 2
b) patch 1 & 2 + patch 3

**Comment by i30817** [comment] 2015-01-07 17:55
i'm sorry about the resolution of the screenshots but gnome-screenshot misbehaves, it doesn't look like this when playing the game.

Screenshot with patch 1 (ddraw: Fix TransformVertices for viewport 2.) and 2 (ddraw: Disable clip-plane-update (ddraw: Disable clip-plane-update (partial revert of commit 4a30db74b1dbad885941970e7caf9815abd7826d).):
![1](https://cloud.githubusercontent.com/assets/757900/5650433/475291da-9696-11e4-850c-cd8d0ffb5ae8.png)



Screenshot with patch 3 (wined3d: Revert commit 439097c810bdcb2bd3f838d2ee47369d1f4d7e8a.) in addition to the previous 2:
![2](https://cloud.githubusercontent.com/assets/757900/5650438/4b632690-9696-11e4-9a64-2ab08f16d36f.png)

As you can see, identical.

**Comment by compholio** [comment] 2015-01-07 18:01
i30817: Oh, you're not at the very beginning of the game...  I was testing on the very first screen of the game.

**Comment by i30817** [comment] 2015-01-07 18:03
This is the intro

**Comment by DarkPlayer** [comment] 2015-01-07 18:04
@i30817 You submitted your comment before the second image finished uploading.

**Comment by i30817** [comment] 2015-01-07 18:12
Fixed, but since it's the same....
Here is a ingame screenshot of the first scene, april is in front of the rock
![3](https://cloud.githubusercontent.com/assets/757900/5650696/a73b7aa6-9698-11e4-8b7b-15e2d024afdd.png)

**Comment by compholio** [comment] 2015-01-07 18:36
Ah, sorry - I'm using the beginning of the _demo_ for testing.  But this proves that the current solution is wrong.

**Comment by i30817** [comment] 2015-01-07 18:51
Eh, i tried that now, demo version 1.61:
![4](https://cloud.githubusercontent.com/assets/757900/5651299/366d224c-969e-11e4-83a2-add6a057007a.png)

So it looks like something related to the hardware or drivers.

**Comment by compholio** [comment] 2015-01-07 19:18
![tlj](https://cloud.githubusercontent.com/assets/1738066/5651744/4e6decd2-9667-11e4-8a0c-6243ea389964.png)
^^ works for me (with the patches)

**Comment by i30817** [comment] 2015-01-07 19:26
I've got console spam like this:
fixme:d3d_surface:surface_load_location Unimplemented copy from WINED3D_LOCATION_TEXTURE_RGB to WINED3D_LOCATION_SYSMEM for depth/stencil buffers.
err:d3d_surface:surface_invalidate_location Surface 0x17c680 does not have any up to date location.
fixme:d3d_surface:surface_unmap Depth / stencil buffer locking is not implemented.
fixme:d3d_surface:surface_load_ds_location No up to date depth stencil location.

Same for you?

**Comment by compholio** [comment] 2015-01-07 19:43
@i30817: Yup, I see that too.

**Comment by i30817** [comment] 2015-01-10 12:31
Is there anyone here that tried these patches using a radeon card like me?

**Comment by deri82** [comment] 2015-01-12 12:00
I just tried the patches. They all aplied cleanly. But the result is the NEARLY the same as in picture

https://cloud.githubusercontent.com/assets/757900/5651299/366d224c-969e-11e4-83a2-add6a057007a.png

ati/amd r9 290, open source drivers, 10.5~git

Not a fully clean prefix, but I tried the game before the patches and there is huge difference between the runs even it doesnt work fully.

**Comment by i30817** [comment] 2015-01-12 13:10
A driver bug?

**Comment by deri82** [comment] 2015-01-12 13:17
Don't know. Did you btw notice if your hero had shadows drawn or not when using patches.

**Comment by i30817** [comment] 2015-01-12 13:27
I just checked, with all the patches applied, there is a artifact in the intro of the character in front of the fireplace, that i'd hesitate to call a shadow (it might just be the mesh completely distorted). Similarly when ingame (and move forward) you can see a  body shadow at aprils feet (which are visible). I'm unsure if it's a real shadow of the kind of trick that was so beloved of 2d games at the time, but for what it worth, it shows the arms/legs moving (on the second orange screen). These screens are the real game beggining not the demo, but i don't see why it would be different.

**Comment by titan73** [comment] 2015-01-12 13:43
I didn't pay attention for the shadow. I tested only the boat with the demo. Is there a windows screenshot that shows the shadows so I can compare?

That would be good to know HW used for each one.

- titan38 => Nvidia GT560M => Ok

**Comment by i30817** [comment] 2015-01-12 13:46
It is noticeable in motion, but it seems ok to me. 
Gallium 0.4 on AMD RV710

**Comment by deri82** [comment] 2015-01-12 13:46
https://www.youtube.com/watch?v=TQCNsAKeLE8&list=PLC67805F668A057FF

around 1minute, I thought that the shadows would be more visible.

**Comment by titan73** [comment] 2015-01-12 13:50
Regarding gray popup and pink text. It seems everybody have these issues without the patches 4 & 5 and have them fixed with them, right ?

**Comment by i30817** [comment] 2015-01-12 13:50
Yes for me.

**Comment by titan73** [comment] 2015-01-12 13:54
@deri82: Is this video from windows or from your wine?

**Comment by deri82** [comment] 2015-01-12 13:56
I assume it's from windows. I haven't uploaded it.

I noticed that I have also transparent issue with mouse cursor which goes away. The blue color isnt drawn at start.

I moved April to the top using stairs where they control the ship by the wheel. You can see 3 charachters drawn there. All are missing some content.

**Comment by titan73** [comment] 2015-01-12 14:11
Which content? Can you do a screenshot?
Btw, something worth mentioning is the resolution and the window/fullscreen, virtual desktop on/off.
I think I tested 1024x768 in virtual desktop.
Yes this blue tells me something. I'll check.

**Comment by i30817** [comment] 2015-01-12 14:14
For me the cursor is partially drawn too. In the ingame intro it's partial in the main camera area and filled in the bottom text area (where the characters dialog goes). In game it gets fixed too - i think when the cursor changes to the 'eye' and back.

**Comment by titan73** [comment] 2015-01-12 14:31
@i30817:
It think the transparent mouse cursor is not a problem. You can see it in the windows video too. It think the cursor is transparent when you cannot interact in the scene.
It seems the shadows are there for you

**Comment by i30817** [comment] 2015-01-12 14:35
that makes sense then.

**Comment by deri82** [comment] 2015-01-12 14:42
![snapshot3](https://cloud.githubusercontent.com/assets/3125379/5704434/f4628ad8-9a79-11e4-840b-5fa3c93d2532.png)

**Comment by deri82** [comment] 2015-01-14 09:18
I was asked to do apitrace for the game using opengl mode, but so far I have been unable. 

I fetched new wine patches from wine git, added the 5 patches and I started to have crash when exit the game.

.
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
wine: Unhandled page fault on read access to 0x0000016c at address 0x405c34 (thread 0009), starting debugger...
Unhandled exception: page fault on read access to 0x0000016c in 32-bit code (0x00405c34).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:00405c34 ESP:0033fd70 EBP:00000000 EFLAGS:00210297(  R- --  I S -A-P-C)
 EAX:00000001 EBX:00000001 ECX:00000000 EDX:00000000
 ESI:00425760 EDI:00000000
Stack dump:
0x0033fd70:  00127640 00425760 00407528 00127640
0x0033fd80:  00425760 00000000 00000001 7c169194
0x0033fd90:  00000000 00425760 00425760 0033fe60
0x0033fda0:  ffffffff 00000000 00127610 7c172fc5
0x0033fdb0:  7b858880 00c811b4 00000000 00418a12
0x0033fdc0:  00400000 00000000 00c811b4 0000000a
Backtrace:
=>0 0x00405c34 in game (+0x5c34) (0x00000000)

**Comment by i30817** [comment] 2015-01-28 23:32
How can i help?

**Comment by deri82** [comment] 2015-01-28 23:43
Can you do apitrace? I was asked to do apitrace with opengl channels and then open bug at mesa drivers and also try other compiler.

**Comment by i30817** [comment] 2015-01-29 01:38
Are we supposed to use api-trace inside wine (windows compiled exe tracing TLJ) or outside, tracing wine running TLJ?

**Comment by i30817** [comment] 2015-01-29 02:46
Ok compiling apitrace for 32 bits sounds like a nightmare, but it's possible to install part of the 32 bits version. How usable is the resulting trace i don't know - but i think you should try it too.
I'm in ubuntu, may be different for you:

First you install 
sudo apt-get install apitrace-gl-frontend
which pulls some stuff including apitrace-gl-tracers:amd64

only with this it will give a load error on gl and give up creating a trace (outside wine):
```
WINEPREFIX=~/.local/share/wineprefixes/TLJ apitrace trace ~/Downloads/wine32/wine Game.exe ERROR: ld.so: object 'glxtrace.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'glxtrace.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```
but you can install 
sudo apt-get install apitrace-gl-tracers:i386

and there are only warnings:
```
WINEPREFIX=~/.local/share/wineprefixes/TLJ apitrace trace ~/Downloads/wine32/wine Game.exe apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: tracing to /home/i30817/Desktop/The Longest Journey/wine-preloader.3.trace
apitrace: redirecting dlopen("libGL.so.1", 0x102)
apitrace: warning: _gl_param_size: unknown GLenum 0x90BC
apitrace: warning: _gl_param_size: unknown GLenum 0x90BC
fixme:win:EnumDisplayDevicesW ((null),0,0x33e568,0x00000000), stub!
apitrace: warning: _gl_param_size: unknown GLenum 0x90BC
apitrace: warning: _gl_param_size: unknown GLenum 0x90BC
```

The resulting trace replays - i only let it go until the start of the intro to let it be under 200mb zipped - still 100 mbs though (it should be enough since the intro shows characters missing polygons).

It's uploading to google drive and i will post a link when done

**Comment by i30817** [comment] 2015-01-29 03:18
I traced with all the patches obviously. If you prefer bare wine or anything else just comment. I wouldn't have any idea of how to open a mesa bug report though (or even if it's necessary).
here it is:
https://drive.google.com/file/d/0BzxkBmaf1EiWblA4dDJ5cmp6MmM/view?usp=sharing

**Comment by i30817** [comment] 2015-02-11 03:50
no progress uh

**Comment by deri82** [comment] 2015-03-02 19:09
I dont know if it's worth to mention but I did patch the most recent wine that you can fetch dated today. The issue is the same. I also touched the source code. It's too complicate to read, but when i disabled one part of the content only shadows were drawn which seem to be drawn correctly. So the issue is more likely in the code I disabled or something related to it.

**Comment by deri82** [comment] 2015-03-02 20:32
![newpicture](https://cloud.githubusercontent.com/assets/3125379/6449783/efdd457e-c12b-11e4-8916-42cef3b8a06a.png)

**Comment by deri82** [comment] 2015-03-02 20:37
![newpicture2](https://cloud.githubusercontent.com/assets/3125379/6449883/bf9b0bc0-c12c-11e4-839a-3241cb72e547.png)

**Comment by deri82** [comment] 2015-03-31 06:52
Death to Spies Moment of Truth: character bodies (player and NPCs) are invisible
https://bugs.winehq.org/show_bug.cgi?id=23407

![puuttuu1](https://cloud.githubusercontent.com/assets/3125379/6913671/87743364-d78b-11e4-8a40-d02a2a5a874a.png)

very similar results !

**Comment by joaopa00** [comment] 2015-06-26 01:36
Hello, I am the reporter of the bug in wine bugzilla.
Good news. I patched the current git wint with 3 patches of comment https://github.com/wine-compholio/wine-staging/issues/232#issuecomment-68217290
With the open intel driver for my integrated videocard, only top of characters are displayed. With the second videocard Nvidia card and propriatary drivers, everything  is fine. That means that the patches are good and that open drivers in mesa are broken.

It remains to add tests to the patch to make it acceptable for Wine, I guess.

**Comment by joaopa00** [comment] 2015-06-26 14:55
@deri82  Talking about Death to spies is pointless since it is a directx9 game not a d3d7 neither ddra. So it is affected by the same bug as Longest journey.

**Comment by compholio** [comment] 2015-06-26 15:59
@joaopa00 The problem on the Intel might be related to another issue, could you try this patch ( https://gist.githubusercontent.com/compholio/7e06399cd021b3880698/raw/3a2279d61550583113e43bc662a0a2e7da36f772/gistfile1.txt ) in addition to the others?

**Comment by joaopa00** [comment] 2015-06-26 19:05
@compholio  > Unfortunately, the patch does not fix the issue with my intel integrated videocard.

**Comment by deri82** [comment] 2015-07-31 03:54
I merged the patches against git-wine
They didnt apply cleanly anymore. 4/5 patches merged, but (taken from subject of the patch) "winex11.drv: Make X11 window rect empty for WS_EX_TRANSPARENT" gave .rej file. 

Link here to the patch http://ix.io/e8l

I didnt investigate the failure I just run the game. This time the full game. It looks pretty much the same. even with 1 patch failing.

**Comment by firesock** [comment] 2015-09-09 22:49
Tried the patches listed https://github.com/wine-compholio/wine-staging/issues/232#issuecomment-69036040 recently, the third one doesn't apply cleanly against git-wine anymore, but it's a simple change that can be done manually.

3b5107d06305972beaa9c5ff147ecbcd99949a75 on a Radeon HD 6850, same as previous screenshots, partially rendered models.

bdaa571c5d7dd59dd28fd1f25cdad5761bfaf4dd on an Intel Haswell, same as previous screenshots, partially rendered models.

**Comment by joaopa00** [comment] 2015-09-26 17:47
@firesock As shown by my previous comment, mesa drivers are broken for this issue. So your test with a Radeon card is pretty useless. Test with a Nvidia card and the propriatary driver.

**Comment by firesock** [comment] 2015-09-26 21:31
@joaopa00 Yes, I was wondering if there have been any improvements since your test. I don't have access to a Nvidia card and setting up proprietary drivers is a pain anyway.

**Comment by joaopa00** [comment] 2015-10-06 08:25
In this link, you can find the transform pipeline for transform vertices with D3DVIEWPORT2

**Comment by slackner** [comment] 2016-01-04 17:41
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.

**Closed by slackner** 2016-01-04 17:41 UTC
Labels: patch, upstream-bug
