### ISSUE TITLE
The Secret World rendering/color and performance issues

### ISSUE THREAD

**Issue by Glog78** [wine-compholio/wine-staging#273] opened 2015-01-13 00:44 UTC
The most anoying thing are the wrong colors during rendering. Here is an example screenshot
![wrongrenderingtsw](https://cloud.githubusercontent.com/assets/7598856/5714044/9007cd60-9ac3-11e4-9c6a-824bf1093b80.jpg)
  
This might be related to the following fixme's  
fixme:d3d_texture:wined3d_texture_generate_mipmaps texture 0x751ea50 stub!  
  
The Secret World uses physx and the following errors are in the logfile:  
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0x2926aaad is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0x4b708b54 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0x774aa982 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0xfceac864 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0xfceac864 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x33c7358c is unimplemented!
fixme:nvapi:unimplemented_stub function 0xfceac864 is unimplemented!
fixme:nvapi:unimplemented_stub function 0x593e8644 is unimplemented!

The performance is horrible without  __GL_THREADED_OPTIMIZATIONS=1 , csmt or native doesn't do it in this case.  

` __GL_THREADED_OPTIMIZATIONS=1 and WINEDEBUG=err+all,warn+all,fixme+all,+d3d,+d3d9,+d3dx` 
[(__warning >900MB extracted and stil 37.2MB as a tar.gz__)](https://dl.dropboxusercontent.com/u/39787677/thesecretworld.log.tar.gz)

**Comment by compholio** [comment] 2015-01-13 00:56
Does it help to disable nvcuda and nvapi in winecfg?  (I realize this will disable PhysX, but it's important to know if this problem is related to the PhysX/CudA/NVAPI codepath)

**Comment by Glog78** [comment] 2015-01-13 01:06
Where to disable it in winecfg. Last ARCH build only has a checkbox for csmt and not for nvcuda. But i can test against a normal wine 1.7.33 -> results:

1.) wrong colors / wrong rendering is happening on normal wine too
2.) nvapi errors don't show up
3.) even with __GL_THREADED_OPTIMIZATIONS=1 the performance is worse than on wine-staging

**Comment by slackner** [comment] 2015-01-13 01:15
@Glog78: There is no explicit checkbox, but instead you have to manually disable the DLLs via `winecfg`. Go to the libraries tab, enter the name of the DLL, click on Add, then Edit the new entry als select "Disabled". After doing that for all libraries the list should look like this:

```
nvapi (diabled)
nvcuda (disabled)
nvcuvid (disabled)
```

Do you know if these color / performance issues are also present with vanilla wine 1.7.34? This is also useful to classify the bug.

**Comment by slackner** [comment] 2015-01-13 01:17
Oh, just saw, you already tested that, I read "wine-staging 1.7.33" somehow. Marking as upstream bug then.

**Comment by Glog78** [comment] 2015-01-13 01:34
wine-staging 1.7.34 with 
`
nvapi (disabled)
nvcuda (disabled)
nvcuvid (disabled)
` 

1.) Wrong rendering still present (colors / lightning ?) in the screenshot
2.) nvapi errors don't show up 

So i would say the nvapi stuff isn't responsible for the wrong rendering but, it might be missing in the wrapper.

**Comment by DarkPlayer** [comment] 2015-01-13 03:52
Regarding the unimplemented nvapi functions: Most of these functions are now implemented in the current git version. The following ones are still missing:
```
0x774aa982 -> NvAPI_GPU_GetMemoryInfo
0xfceac864 -> NvAPI_D3D_GetObjectHandleForResource
```

**Comment by DarkPlayer** [comment] 2015-01-14 21:34
`NvAPI_D3D_GetObjectHandleForResource` stub was added in 93764fd3d417f837cf2a111e0d4aab23f7ce7d5f.

**Comment by Glog78** [comment] 2015-01-17 10:20
Hi DarkPlayer i dunno if it helps you but this is a test for the actual staging git :)

fixme:nvapi:unimplemented_stub function 0x774aa982 is unimplemented!
fixme:nvapi:NvAPI_D3D_GetObjectHandleForResource (0x626beb18, 0x133998ec, 0x33e674): stub
fixme:nvapi:NvAPI_D3D_GetObjectHandleForResource (0x626beb18, 0x133998fc, 0x33e674): stub
fixme:nvapi:NvAPI_D3D_GetObjectHandleForResource (0x626beb18, 0x1339990c, 0x33e674): stub

**Comment by deri82** [comment] 2015-07-20 19:17
Has there been any improvements?

**Comment by slackner** [comment] 2016-01-04 17:43
Hi everyone,

About one year ago, we announced that we would like to move to more advanced bug tracker. We are sorry for the inconvenience, but now its time to say finally goodbye to the old one. This means, all remaining opened bugs (including this one!) will be closed, and no longer available. If you still need any information from the old bugtracker, please write a mail to webmaster@fds-team.de.

More important, if your issue still exists, please open a new bug report at one of the places mentioned below. For bug reports, please attach terminal output from a recent Wine version (preferably >= 1.8). Please note that in the meantime, Wine Staging has become an official part of WineHQ, so if your issue is already tracked at winehq.org, there is NO NEED to open a new bug report for it. Feel free to add the Wine Staging maintainers (sebastian@fds-team.de, michael@fds-team.de) as CC if you want us to take a look at your bug report.

**NEW BUG TRACKERS:**

* For all Wine AND Wine Staging bugs. USE THIS IF IN DOUBT. (*)
  https://bugs.winehq.org/enter_bug.cgi?product=Wine

* For packaging issues:
  https://bugs.winehq.org/enter_bug.cgi?product=Packaging

* For patch submission:
  https://bugs.wine-staging.com/enter_bug.cgi

Best regards,
Sebastian

----

(*) The "Wine Staging" product in the winehq bugtracker should only be used, when your problem turns out to be a regression introduced in "Wine Staging". Since most problems also occur with Wine, it is recommended to open your bug in the "Wine" product, unless someone can show that it doesn't occur with the development branch.

**Closed by slackner** 2016-01-04 17:43 UTC
Labels: upstream-bug
